# IDA: Assignment 2

### Deadline: October 3 (until 23:59)


**Instructions:** All answers should be provided in the notebook and then submitted to Moodle. Name of notebook should be in following format:
 - Name_group_Assignment2.ipynb (ex. Tony_Stark_2009_Assignment1.ipynb). PLEASE, use exactly the **same format.**
 - Try to use fewer cells for compilation (for example, you can use print for several answers, instead of printing each answer on a separate cell)
 - **PLEASE:** submit only one jupyter notebook (no zip or csv files) and with your names as in the instruction. Ohterwise, there will be punishment of 30% from your assignment mark.
 - **IMPORTANT NOTE:** you will get points only for correct answers, not for trials or wrong answers. Your notebook should run when we press **"Restart Kernel"** and then press **"Run All"**. We are going to check answers only after doing that. If your code do not compile and stops at any question, you will get zero for that question.

## Q1 (10%)
Using **list comprehension** create a new list from `list_q1_1` and `list_q1_2`. For the values at the same position (index), you should have sum of elements if element of `list_q1_1` is smaller (strictly) than the element of `list_q1_2`. Otherwise, you should take their difference. 

***Note:*** *in the obtained list all values should be positive.*

In [ ]:
list_q1_1 = [41, 21, 96, 34, 65, 46, 79, 73, 49, 85, 63, 51, 93, 84, 29, 62, 95, 39, 72, 66]
print(list_q1_1)

In [4]:
list_q1_2 = [95, 76, 92, 91, 49, 61, 68, 32, 50, 29, 48, 82, 33, 81, 39, 69, 84, 74, 89, 15]
print(list_q1_2)

[95, 76, 92, 91, 49, 61, 68, 32, 50, 29, 48, 82, 33, 81, 39, 69, 84, 74, 89, 15]


In [9]:
#[expression1 if condition1 else expression2 for item in list]
new_list = [ list_q1_1[i] + list_q1_2[i]  if list_q1_1[i] < list_q1_2[i]  else list_q1_1[i] - list_q1_2[i] for i in range(len(list_q1_1))]
print(new_list)


[136, 97, 4, 125, 16, 107, 11, 41, 99, 56, 15, 133, 60, 3, 68, 131, 11, 113, 161, 51]


## Q2 (10%)
Using **list comprehension** on `list_q2_1` and `list_q2_2` create a new list containing value pairs, where one of them is divisible by another, but do not include two equal elements. For example, (13, 91) should be included, but (91,91) should not).

In [19]:
list_q2_1 = [97, 29, 43, 96, 91, 22, 51, 83, 31, 13,
             62, 19, 23, 26, 50, 70, 84, 67, 36, 35]
print(list_q2_1)

[97, 29, 43, 96, 91, 22, 51, 83, 31, 13, 62, 19, 23, 26, 50, 70, 84, 67, 36, 35]


In [20]:
list_q2_2 = [31, 63, 98, 91, 46, 71, 37, 70, 75, 33,
             74, 77, 40, 10, 11, 57, 84, 64, 18, 28]
print(list_q2_2)

[31, 63, 98, 91, 46, 71, 37, 70, 75, 33, 74, 77, 40, 10, 11, 57, 84, 64, 18, 28]


In [21]:
# your code here
new_list = [ [ (i, j) for i in list_q2_1 for j in list_q2_1 if (i % j == 0 or j % i == 0) and i != j ]]
print(new_list)

[[(91, 13), (31, 62), (13, 91), (13, 26), (62, 31), (26, 13), (70, 35), (35, 70)]]


## Q3 (10%)
Using **list comprehension** obtain a list of all 2-digits prime numbers (for example, 13, 17, 19...).

***Note:*** *it can be done with one line of code.*

In [30]:
# your code here
new_list = [ i for i in range(10,100) if 0 not in [ i % j for j in range(2,int(i**0.5)+1)] ]
print(new_list)

[11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


## Q4 (10%)


Using **list comprehension** create a windowing lists of 3 elements at a time with step 1 for `list_q4`. 

Your result should look as following: [[48, 95, 11], [95, 11, 46], [11, 46, 76],..]

***Note:*** *it can be done with one line of code.*

In [32]:
list_q4 = [48, 95, 11, 46, 76, 75, 35, 78, 81, 58, 
           17, 26, 97, 63, 93, 57, 28, 85, 54, 62]
print(list_q4)

[48, 95, 11, 46, 76, 75, 35, 78, 81, 58, 17, 26, 97, 63, 93, 57, 28, 85, 54, 62]


In [46]:
# your code here
new_list = [ list_q4[i:i+3] for i in range(len(list_q4)-2)]
# for i in range(len(list_q4)-2):
#     new_list.append(list_q4[i:i+3])

print(new_list)

[[48, 95, 11], [95, 11, 46], [11, 46, 76], [46, 76, 75], [76, 75, 35], [75, 35, 78], [35, 78, 81], [78, 81, 58], [81, 58, 17], [58, 17, 26], [17, 26, 97], [26, 97, 63], [97, 63, 93], [63, 93, 57], [93, 57, 28], [57, 28, 85], [28, 85, 54], [85, 54, 62]]


## Q5 (10%)
For the string below using **dictionary comprihension** create a dictionary, where key - possible word length, and value - number of words of this length. 

***Note:*** *you should not consider keys which are not appearing in the text.*

In [2]:
string_q5 = "From they fine john he give of rich he. They age and draw mrs like. Improving end distrusts may instantly was household applauded incommode. Why kept very ever home mrs. Considered sympathize ten uncommonly occasional assistance sufficient not. Letter of on become he tended active enable to. Vicinity relation sensible sociable surprise screened no up as.Death weeks early had their and folly timed put. Hearted forbade on an village ye in fifteen. Age attended betrayed her man raptures laughter. Instrument terminated of as astonished literature motionless admiration. The affection are determine how performed intention discourse but. On merits on so valley indeed assure of. Has add particular boisterous uncommonly are. Early wrong as so manor match. Him necessary shameless discovery consulted one but."
print(string_q5)

From they fine john he give of rich he. They age and draw mrs like. Improving end distrusts may instantly was household applauded incommode. Why kept very ever home mrs. Considered sympathize ten uncommonly occasional assistance sufficient not. Letter of on become he tended active enable to. Vicinity relation sensible sociable surprise screened no up as.Death weeks early had their and folly timed put. Hearted forbade on an village ye in fifteen. Age attended betrayed her man raptures laughter. Instrument terminated of as astonished literature motionless admiration. The affection are determine how performed intention discourse but. On merits on so valley indeed assure of. Has add particular boisterous uncommonly are. Early wrong as so manor match. Him necessary shameless discovery consulted one but.


In [6]:
# # your code here
# # new_string = {len(word): len([ text for text in string_q5.split(' ') if len(text) == len(word) ]) for word in string_q5.split(' ') }   
# # print(new_string)
# string_q5 = string_q5.maketrans('.',' ')
def remove_symbol(string_q5):
    import string
    word = string.punctuation
    replace = " "*len(word)
    text = str.maketrans(word,replace)
    string_q5 = string_q5.translate(text)
    new_string = { len(word): [ text for text in string_q5.split(' ') if len(text) == len(word) ] for word in string_q5.split(' ') }
    return new_string
remove_symbol(string_q5)
# string_q5 = ''.join(ch for ch in text if ch not in punctuation)
# string_q5 = string_q5.punctuation()

# string_q5 = string_q5.replace('.'," ")

# new_string = { len(word): [ text for text in string_q5.split(' ') if len(text) == len(word) ] for word in string_q5.split(' ') }
# print(new_string)

{4: ['From',
  'they',
  'fine',
  'john',
  'give',
  'rich',
  'They',
  'draw',
  'like',
  'kept',
  'very',
  'ever',
  'home'],
 2: ['he',
  'of',
  'he',
  'of',
  'on',
  'he',
  'to',
  'no',
  'up',
  'as',
  'on',
  'an',
  'ye',
  'in',
  'of',
  'as',
  'On',
  'on',
  'so',
  'of',
  'as',
  'so'],
 0: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 3: ['age',
  'and',
  'mrs',
  'end',
  'may',
  'was',
  'Why',
  'mrs',
  'ten',
  'not',
  'had',
  'and',
  'put',
  'Age',
  'her',
  'man',
  'The',
  'are',
  'how',
  'but',
  'Has',
  'add',
  'are',
  'Him',
  'one',
  'but'],
 9: ['Improving',
  'distrusts',
  'instantly',
  'household',
  'applauded',
  'incommode',
  'affection',
  'determine',
  'performed',
  'intention',
  'discourse',
  'necessary',
  'shameless',
  'discovery',
  'consulted'],
 10: ['Considered',
  'sympathize',
  'uncommonly',
  'occasional',
  'assistance',
  'sufficient',
  'Instrument',
  'terminated',
  'astonished',
  'li

## Q6 (10%)
Using numpy create two arbitrary matrices A and B of size 3x3 with only 2-digit numbers. And then apply different matrix operations:
1. addition
2. subtraction
3. pointwise multiplication
4. pointwise division
5. matrix dot product
6. transpose
7. determinant
8. rank
9. inverse

In [36]:
import numpy as np

In [37]:
# your code here
A = np.array([[10,12,13],[14,15,16],[17,18,19]])
B = np.array([[19,18,17],[16,15,14],[13,12,10]])
print("#1\n",np.add(A,B))
print("#2\n",np.subtract(A,B))
print("#3\n",np.multiply(A,B))
print("#4\n",np.divide(A,B))
print("#5\n",np.dot(A,B))
print("#6\n",np.transpose(A))
print("#7\n",np.linalg.det(A+B))
print("#8\n",np.argsort(A+B))
print("#9\n",np.linalg.inv(A+B))

#1
 [[29 30 30]
 [30 30 30]
 [30 30 29]]
#2
 [[-9 -6 -4]
 [-2  0  2]
 [ 4  6  9]]
#3
 [[190 216 221]
 [224 225 224]
 [221 216 190]]
#4
 [[0.52631579 0.66666667 0.76470588]
 [0.875      1.         1.14285714]
 [1.30769231 1.5        1.9       ]]
#5
 [[551 516 468]
 [714 669 608]
 [858 804 731]]
#6
 [[10 14 17]
 [12 15 18]
 [13 16 19]]
#7
 30.000000000000004
#8
 [[0 1 2]
 [0 1 2]
 [2 0 1]]
#9
 [[-1.          1.          0.        ]
 [ 1.         -1.96666667  1.        ]
 [-0.          1.         -1.        ]]


## Q7 (10%)
For the list below obtain numpy array and then do the following steps:
1. Find all indexes for values between 40 and 60 (both included).
2. Find all values between 40 and 60 (both included).
3. Find all numbers divisible by 3 or 5 or 7.
4. Find all prime numbers in this array (you may use list obtained in Q3).

In [90]:
list_q7 = [53, 58, 93, 96, 40, 97, 95, 24, 27, 61, 
           15, 25, 47, 22, 45, 50, 99, 37, 13, 17, 
           90, 13, 23, 54, 80, 83, 98, 14, 70, 30]
print(list_q7)

[53, 58, 93, 96, 40, 97, 95, 24, 27, 61, 15, 25, 47, 22, 45, 50, 99, 37, 13, 17, 90, 13, 23, 54, 80, 83, 98, 14, 70, 30]


In [92]:
# your code here
#1
a = np.array(list_q7)
print("#1\n",np.where(np.logical_and(a > 39, a < 61)))
#2
print("#2\n",a[(a > 39)*(a < 61)] )
#3 
print("#3\n",a[np.logical_or(a%3==0, a%5==0, a%7==0)])
#4
arr = np.array(list_q7)
# arr2 = np.array(que3_list)
print("#4\n",arr)

#1
 (array([ 0,  1,  4, 12, 14, 15, 23], dtype=int64),)
#2
 [53 58 40 47 45 50 54]
#3
 [93 96 40 95 24 27 15 25 45 50 99 90 54 80 70 30]
#4
 [53 58 93 96 40 97 95 24 27 61 15 25 47 22 45 50 99 37 13 17 90 13 23 54
 80 83 98 14 70 30]


## Q8 (10%)
Do the following tasks:
1. Create an array of all 3-digit numbers divisible by 33. 
2. Create an array of 19 elements betweem 10 and 100.
3. Create an array of size 20 with random 2-digit values. Replace all numbers divisible by 3 to 'abc'.
4. Create an array of size 20 with random 2-digit values. Find 3 smallest and 3 largest elements. 

In [84]:
# your code here
print("#1")
arr = np.arange(100, 1000).reshape(900)
print(arr[arr%33 == 0])

print("#2")
m = np.random.randint(10, 100, (19))
print(m)

a = np.array([[10,12,13],[14,15,16],[17,18,19], 
             [20,28,27],[26,25,24],[23,22,30],
             [39,38,37],[36,35,34],[33,32,40],
             [49,48,47],[46,45,44],[43,42,40],
             [49,48,47],[46,45,44],[43,42,50],
             [59,58,57],[56,55,54],[53,52,60],[69,68,67]])
print(a)

#3
c = np.random.randint(10, 100, (20))
print("#3\n",c)
print(np.where(c%3 == 0, 'abc', c))
#4
arr = np.random.randint(10, 100, (20))
print("#4\n",arr)
n = 3
print("smallest\n",np.partition(arr,n)[:n])
print("largest\n",np.partition(arr,-n)[-n:])

#1
[132 165 198 231 264 297 330 363 396 429 462 495 528 561 594 627 660 693
 726 759 792 825 858 891 924 957 990]
#2
[62 30 13 53 55 94 47 98 14 11 71 85 36 87 86 81 89 56 88]
[[10 12 13]
 [14 15 16]
 [17 18 19]
 [20 28 27]
 [26 25 24]
 [23 22 30]
 [39 38 37]
 [36 35 34]
 [33 32 40]
 [49 48 47]
 [46 45 44]
 [43 42 40]
 [49 48 47]
 [46 45 44]
 [43 42 50]
 [59 58 57]
 [56 55 54]
 [53 52 60]
 [69 68 67]]
#3
 [49 98 23 27 14 13 93 86 95 59 23 26 21 94 44 42 56 80 87 16]
['49' '98' '23' 'abc' '14' '13' 'abc' '86' '95' '59' '23' '26' 'abc' '94'
 '44' 'abc' '56' '80' 'abc' '16']
#4
 [32 95 37 32 67 78 58 16 88 28 46 12 52 94 63 26 83 28 65 65]
smallest
 [12 16 26]
largest
 [88 94 95]


## Q9 (10%)
Create a matrix of size 4x4 with random 2-digit numbers. Do the following tasks:
1. Find mean along rows and mean along columns.
2. Find max along rows and max along columns.
3. Find indexes of min and max values.
4. Iteratre over matrix, and print its index as (i,j) and corresponding value. For example, Index: (1,1), Value: 50.

In [65]:
# your code here
#1
a = np.random.randint(10,100, (4,4))
print("#1\n")
#column means
print(a.mean(axis=0))
#row means
print(a.mean(axis=1),"\n")
#2
print("#2\n")
print(a.max(axis=0))
print(a.max(axis=1),"\n")
#3
print("#3\n")
print(np.argmax(a))
print(np.argmin(a),"\n")
#4
print("#4\n")
for index, value in np.ndenumerate(a):
    print("index:",index, "value:", value)

#1

[32.75 67.25 38.   49.5 ]
[41.75 58.75 41.   46.  ] 

#2

[57 99 52 83]
[73 88 57 99] 

#3

13
11 

#4

index: (0, 0) value: 14
index: (0, 1) value: 37
index: (0, 2) value: 43
index: (0, 3) value: 73
index: (1, 0) value: 37
index: (1, 1) value: 88
index: (1, 2) value: 27
index: (1, 3) value: 83
index: (2, 0) value: 57
index: (2, 1) value: 45
index: (2, 2) value: 52
index: (2, 3) value: 10
index: (3, 0) value: 23
index: (3, 1) value: 99
index: (3, 2) value: 30
index: (3, 3) value: 32


## Q10 (10%)
Create a matrix of size 5x5 with random 2-digit numbers. Do the following tasks:
1. Reverse both along rows and columns.
2. Sort along rows in descending order.
3. Sort along columns in descending order.
4. Sort all 25 elements in descending order, i.e. at index (1,1) you should have the largest element, and at index (5,5) the smallest element. 

In [66]:
# your code here
#1
a = np.random.randint(1,100, (5,5))
print("#1:\n",np.flip(a))
#2
print("#2:\n",np.sort(a)[::-1])
#3
print("#3:\n",a[a[:, 0].argsort()])
#4
print("#4:\n",np.sort(a))
print("\n",-np.sort(-a))

#1:
 [[74 25 95 36 50]
 [88 67  4 59 61]
 [53 57 36 70 38]
 [37 36 32 99  7]
 [76 92  7 61 93]]
#2:
 [[25 36 50 74 95]
 [ 4 59 61 67 88]
 [36 38 53 57 70]
 [ 7 32 36 37 99]
 [ 7 61 76 92 93]]
#3:
 [[ 7 99 32 36 37]
 [38 70 36 57 53]
 [50 36 95 25 74]
 [61 59  4 67 88]
 [93 61  7 92 76]]
#4:
 [[ 7 61 76 92 93]
 [ 7 32 36 37 99]
 [36 38 53 57 70]
 [ 4 59 61 67 88]
 [25 36 50 74 95]]

 [[93 92 76 61  7]
 [99 37 36 32  7]
 [70 57 53 38 36]
 [88 67 61 59  4]
 [95 74 50 36 25]]


---

### Evaluation (Keep it!)

| Question | Mark     | Comment   
|:-------:|:--------:|:----------------------
| 1       |   10/10    |     
| 2       |   10/10     | 
| 3       |   10/10     | 
| 4       |   10/10     | 
| 5       |   10/10    |     
| 6       |   10/10     | 
| 7       |   10/10     | 
| 8       |   10/10     | 
| 9       |   10/10     | 
| 10       |   10/10     | 
|**Total**|**100/100**  | 
